/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#444652",
        "on-background": "#1a1c1b",
        "on-error": "#ffffff",
        tertiary: "#535561",
        "surface-variant": "#e2e3e1",
        "on-tertiary-container": "#f0f0ff",
        "on-primary": "#ffffff",
        surface: "#f9f9f7",
        "inverse-primary": "#c1c1ff",
        outline: "#777586",
        "tertiary-fixed-dim": "#c5c5d4",
        "surface-container": "#eeeeec",
        "inverse-surface": "#2f3130",
        "on-secondary-container": "#636262",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-fixed": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c7c4d7",
        "surface-container-highest": "#e2e3e1",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#322fba",
        "primary-container": "#5b5ce2",
        "tertiary-container": "#6b6d7a",
        "on-primary-container": "#f2efff",
        primary: "#4141c8",
        "surface-bright": "#f9f9f7",
        "on-tertiary-fixed": "#191b25",
        "surface-container-high": "#e8e8e6",
        secondary: "#5f5e5e",
        "secondary-container": "#e2dfde",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f4f4f2",
        "surface-tint": "#4b4bd2",
        "inverse-on-surface": "#f1f1ef",
        background: "#f9f9f7",
        "on-surface-variant": "#464554",
        "on-secondary-fixed-variant": "#474746",
        "on-surface": "#1a1c1b",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#08006b",
        "primary-fixed": "#e1dfff",
        "tertiary-fixed": "#e1e1f0",
        "surface-dim": "#dadad8",
        "primary-fixed-dim": "#c1c1ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-4xl": "6rem",
        "container-narrow": "720px",
        "space-3xl": "4.5rem",
        "space-md": "1rem",
        "container-wide": "1160px",
        "space-xl": "2rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-2xl": "3rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        display: ["Geist", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-mono-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-mobile": ["Geist", "sans-serif"],
      },
      fontSize: {
        display: ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "label-code": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "30px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-mono-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "display-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
